// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire.go:

func InitializeEvent(msg string) Event {
	message := NewMessage1(msg)
	greeter := NewGreeter1(message)
	event := NewEvent1(greeter)
	return event
}
